/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exam {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'timeLimitMinutes' : bigint,
  'questions' : Array<Question>,
}
export interface ExamResult {
  'id' : string,
  'studentEmail' : string,
  'studentName' : string,
  'answers' : Array<Array<bigint>>,
  'submittedAt' : bigint,
  'score' : bigint,
  'totalQuestions' : bigint,
  'examId' : string,
}
export interface PublicExam {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'timeLimitMinutes' : bigint,
  'questions' : Array<PublicQuestion>,
}
export interface PublicQuestion {
  'id' : string,
  'text' : string,
  'allowMultiple' : boolean,
  'options' : Array<string>,
}
export interface Question {
  'id' : string,
  'text' : string,
  'correctAnswerIndices' : Array<bigint>,
  'allowMultiple' : boolean,
  'options' : Array<string>,
}
export interface StudentProfile {
  'name' : string,
  'results' : Array<ExamResult>,
  'email' : string,
  'totalExams' : bigint,
  'averageScore' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createExam' : ActorMethod<[Exam], undefined>,
  'deleteExam' : ActorMethod<[string], undefined>,
  'getActiveExamById' : ActorMethod<[string], [] | [PublicExam]>,
  'getActiveExams' : ActorMethod<[], Array<PublicExam>>,
  'getAllExamResults' : ActorMethod<[], Array<ExamResult>>,
  'getAllStudentProfiles' : ActorMethod<[], Array<StudentProfile>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExam' : ActorMethod<[string], [] | [Exam]>,
  'getExamResult' : ActorMethod<[string], [] | [ExamResult]>,
  'getExamResultsByExamId' : ActorMethod<[string], Array<ExamResult>>,
  'getExamResultsByStudentEmail' : ActorMethod<[string], Array<ExamResult>>,
  'getStudentProfile' : ActorMethod<[string], [] | [StudentProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitExamResult' : ActorMethod<
    [string, string, string, Array<Array<bigint>>],
    { 'score' : bigint, 'totalQuestions' : bigint }
  >,
  'toggleExamActive' : ActorMethod<[string], undefined>,
  'updateExam' : ActorMethod<[string, Exam], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];