/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
  'correctAnswerIndices' : IDL.Vec(IDL.Nat),
  'allowMultiple' : IDL.Bool,
  'options' : IDL.Vec(IDL.Text),
});
export const Exam = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'timeLimitMinutes' : IDL.Nat,
  'questions' : IDL.Vec(Question),
});
export const PublicQuestion = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
  'allowMultiple' : IDL.Bool,
  'options' : IDL.Vec(IDL.Text),
});
export const PublicExam = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'timeLimitMinutes' : IDL.Nat,
  'questions' : IDL.Vec(PublicQuestion),
});
export const ExamResult = IDL.Record({
  'id' : IDL.Text,
  'studentEmail' : IDL.Text,
  'studentName' : IDL.Text,
  'answers' : IDL.Vec(IDL.Vec(IDL.Nat)),
  'submittedAt' : IDL.Int,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'examId' : IDL.Text,
});
export const StudentProfile = IDL.Record({
  'name' : IDL.Text,
  'results' : IDL.Vec(ExamResult),
  'email' : IDL.Text,
  'totalExams' : IDL.Nat,
  'averageScore' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createExam' : IDL.Func([Exam], [], []),
  'deleteExam' : IDL.Func([IDL.Text], [], []),
  'getActiveExamById' : IDL.Func([IDL.Text], [IDL.Opt(PublicExam)], ['query']),
  'getActiveExams' : IDL.Func([], [IDL.Vec(PublicExam)], ['query']),
  'getAllExamResults' : IDL.Func([], [IDL.Vec(ExamResult)], ['query']),
  'getAllStudentProfiles' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExam' : IDL.Func([IDL.Text], [IDL.Opt(Exam)], ['query']),
  'getExamResult' : IDL.Func([IDL.Text], [IDL.Opt(ExamResult)], ['query']),
  'getExamResultsByExamId' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExamResult)],
      ['query'],
    ),
  'getExamResultsByStudentEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExamResult)],
      ['query'],
    ),
  'getStudentProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitExamResult' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Vec(IDL.Nat))],
      [IDL.Record({ 'score' : IDL.Nat, 'totalQuestions' : IDL.Nat })],
      [],
    ),
  'toggleExamActive' : IDL.Func([IDL.Text], [], []),
  'updateExam' : IDL.Func([IDL.Text, Exam], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Text,
    'text' : IDL.Text,
    'correctAnswerIndices' : IDL.Vec(IDL.Nat),
    'allowMultiple' : IDL.Bool,
    'options' : IDL.Vec(IDL.Text),
  });
  const Exam = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'timeLimitMinutes' : IDL.Nat,
    'questions' : IDL.Vec(Question),
  });
  const PublicQuestion = IDL.Record({
    'id' : IDL.Text,
    'text' : IDL.Text,
    'allowMultiple' : IDL.Bool,
    'options' : IDL.Vec(IDL.Text),
  });
  const PublicExam = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'timeLimitMinutes' : IDL.Nat,
    'questions' : IDL.Vec(PublicQuestion),
  });
  const ExamResult = IDL.Record({
    'id' : IDL.Text,
    'studentEmail' : IDL.Text,
    'studentName' : IDL.Text,
    'answers' : IDL.Vec(IDL.Vec(IDL.Nat)),
    'submittedAt' : IDL.Int,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'examId' : IDL.Text,
  });
  const StudentProfile = IDL.Record({
    'name' : IDL.Text,
    'results' : IDL.Vec(ExamResult),
    'email' : IDL.Text,
    'totalExams' : IDL.Nat,
    'averageScore' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createExam' : IDL.Func([Exam], [], []),
    'deleteExam' : IDL.Func([IDL.Text], [], []),
    'getActiveExamById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicExam)],
        ['query'],
      ),
    'getActiveExams' : IDL.Func([], [IDL.Vec(PublicExam)], ['query']),
    'getAllExamResults' : IDL.Func([], [IDL.Vec(ExamResult)], ['query']),
    'getAllStudentProfiles' : IDL.Func(
        [],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExam' : IDL.Func([IDL.Text], [IDL.Opt(Exam)], ['query']),
    'getExamResult' : IDL.Func([IDL.Text], [IDL.Opt(ExamResult)], ['query']),
    'getExamResultsByExamId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExamResult)],
        ['query'],
      ),
    'getExamResultsByStudentEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExamResult)],
        ['query'],
      ),
    'getStudentProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitExamResult' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Vec(IDL.Nat))],
        [IDL.Record({ 'score' : IDL.Nat, 'totalQuestions' : IDL.Nat })],
        [],
      ),
    'toggleExamActive' : IDL.Func([IDL.Text], [], []),
    'updateExam' : IDL.Func([IDL.Text, Exam], [], []),
  });
};

export const init = ({ IDL }) => { return []; };